apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.backend.name }}"

spec:
  selector:
    component: "{{ .Values.backimage.name }}"
  type: "{{ .Values.service.backend.type }}"
  ports:
    - port: 8080
      targetPort: 8080