---
  - name: Create a subnet group for RDS
    hosts: localhost
    tasks:
      - name: Create Subnet_Group
        register: unameout
        command: "sh postgresdbinstall.sh"
      - debug:
          var: unameout.stdout_lines 