---
  - name: Creating Postgress DB
    hosts: localhost
    tasks:
      - name: Create Postgresql DB
        register: unameout
        command: "sh postgresdbinstall.sh"
      - debug:
          var: unameout.stdout_lines 