---
  - name: Creating Postgress DB
    hosts: localhost
    tasks:
      - name: Create Postgress DB
        register: unameout
        command: "sh aws s3 ls"
      - debug:
          var: unameout.stdout_lines 