---
  - name: Create a subnet group for RDS 
    hosts: localhost
    tasks:
      - name: Creating Subnet_Group
        register: unameout
        command: "sh postgres.sh"
      - debug:
          var: unameout.stdout_lines
