apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeploy

spec:
  replicas: 3
  selector:
    matchLabels:
      component: backendapp
  template:
    metadata:
      labels:
        component: backendapp
    spec:
      containers:
      - name: backendapp
        image: smartcloud2022/validator-backend-image:latest
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddeploy

spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontendapp
  template:
    metadata:
      labels:
        component: frontendapp
    spec:
      containers:
      - name: frontendapp
        image: smartcloud2022/validator-frontend-image:latest
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: servicebackend

spec:
  selector:
    component: backendapp
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: servicefrontend

spec:
  selector:
    component: frontendapp
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8081
---

apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: jumiaingress

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: servicefrontend
                port:
                  number: 80
