apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: jumia_validator_ingress

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend_service
                port:
                  number: 80