#!/bin/bash

sudo hostnamectl set-hostname "k8smaster"

#Set hostname and add entries in the hosts file
sudo cat << EOF > /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

172.31.11.90     k8smaster.jumia.local k8smaster
172.31.44.230    k8sworker1.jumia.local k8sworker1
172.31.40.53     k8sworker2.jumia.local k8sworker2
172.31.41.9      k8sworker3.jumia.local k8sworker3
EOF

 sudo swapoff -a
 sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

sudo tee /etc/modules-load.d/containerd.conf <<EOF
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter


sudo cat <<EOF > /etc/sysctl.d/kubernetes.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF 

sudo sysctl --system

sudo apt install -y curl gnupg software-properties-common apt-transport-https ca-certificates
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg

 sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
 
 sudo apt update
 
 sudo apt install -y containerd.io
 
 containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1

 sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

 sudo systemctl restart containerd
 sudo systemctl enable containerd

 curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
 sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"

 sudo apt update
 sudo apt install -y kubelet kubeadm kubectl
 sudo apt-mark hold kubelet kubeadm kubectl

sudo kubeadm init --control-plane-endpoint=k8smaster

 
 kubeadm join k8smaster:6443 --token rql41i.atg2cmd2fgavod6f --discovery-token-ca-cert-hash sha256:395dbf6fa441046a21a0ba3e7f58984e64098b511aefe98c6e3a6928b32357b4
 
 # Install helm 
 wget https://get.helm.sh/helm-v3.9.3-linux-amd64.tar.gz
 tar xvf helm-v3.9.3-linux-amd64.tar.gz
 sudo mv linux-amd64/helm /usr/local/bin
 rm helm-v3.4.1-linux-amd64.tar.gz
 rm -rf linux-amd64
 helm version
 
 
 


